# Generated by Django 3.2 on 2022-08-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convention', '0004_block_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('is_author_notified', models.BooleanField(default=False, verbose_name='Автор получил ответ')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='convention.attendee', verbose_name='Получатель')),
            ],
        ),
    ]
