# Generated by Django 3.2 on 2022-08-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0005_initial_default_values'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='convention.attendee', verbose_name='Автор вопроса'),
            preserve_default=False,
        ),
    ]
