# Generated by Django 3.2 on 2022-08-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20220805_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос участника', 'verbose_name_plural': 'Вопросы участников'},
        ),
    ]
