# Generated by Django 3.2 on 2022-08-07 12:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0007_auto_20220806_2100'),
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата транзакции'),
        ),
        migrations.AddField(
            model_name='donate',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='convention.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donate',
            name='telegram_id',
            field=models.IntegerField(default=0, verbose_name='ID в телеграмме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(65), django.core.validators.MaxValueValidator(1000)], verbose_name='Сумма'),
        ),
    ]
