# Generated by Django 3.2 on 2022-08-07 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convention', '0007_auto_20220806_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время создания')),
                ('released_on', models.DateTimeField(editable=False, null=True, verbose_name='Время рассылки оповещения')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anouncements', to='convention.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
            },
        ),
    ]
