# Generated by Django 3.2 on 2022-08-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='ID в телеграмме')),
                ('telegram_username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Логин в телеграмме')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название блока')),
                ('starts_at', models.DateTimeField(verbose_name='Время начала блока')),
                ('ends_at', models.DateTimeField(verbose_name='Время окончания блока')),
            ],
            options={
                'verbose_name': 'Блок докладов',
                'verbose_name_plural': 'Блоки докладов',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название ивента')),
                ('starting_date', models.DateField(verbose_name='День начала ивента')),
                ('ending_date', models.DateField(verbose_name='День окончания ивента')),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название выступления')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='convention.block', verbose_name='Блок')),
                ('speakers', models.ManyToManyField(related_name='presentations', to='convention.Attendee', verbose_name='Спикеры')),
            ],
            options={
                'verbose_name': 'Выступление',
                'verbose_name_plural': 'Выступления',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название потока')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='convention.event', verbose_name='Ивент')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='convention.flow', verbose_name='Поток'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='convention.event', verbose_name='Ивент'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('telegram_id', 'event')},
        ),
    ]
