# Generated by Django 3.2 on 2022-08-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID в телеграмме')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
