# Generated by Django 3.2 on 2022-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название блока'),
        ),
    ]
