# Generated by Django 3.2 on 2022-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Логин в телеграмме'),
        ),
    ]
