# Generated by Django 3.2 on 2022-08-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0003_auto_20220804_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание блока'),
        ),
    ]
