# Generated by Django 3.2 on 2022-08-04 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0003_auto_20220804_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='speaker',
        ),
        migrations.AddField(
            model_name='attendee',
            name='events',
            field=models.ManyToManyField(related_name='attendees', to='convention.Event', verbose_name='Ивенты'),
        ),
        migrations.AddField(
            model_name='block',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время окончания блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ending_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='День окончания ивента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='День начала ивента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='speakers',
            field=models.ManyToManyField(related_name='presentations', to='convention.Attendee', verbose_name='Спикеры'),
        ),
        migrations.AlterField(
            model_name='block',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='convention.flow', verbose_name='Поток'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='convention.event', verbose_name='Ивент'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='convention.block', verbose_name='Блок'),
        ),
    ]
