# Generated by Django 3.2 on 2022-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0006_alter_event_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ('order_number',), 'verbose_name': 'Выступление', 'verbose_name_plural': 'Выступления'},
        ),
        migrations.AddField(
            model_name='presentation',
            name='order_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер по порядку'),
        ),
    ]
